spring.application.name=report
spring.datasource.url=jdbc:postgresql://localhost:5432/MYBNTEST
spring.datasource.username=postgres
spring.datasource.password=M@#Admin#256

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
server.port=8010

bakong.token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoiYTVkY2I1OGUzZTYzNGQ4NSJ9LCJpYXQiOjE3NzgzNDY0ODgsImV4cCI6MTc4NjEyMjQ4OH0.bxiV_mA1FmkeOfqYApowf02trbrEah20GGoiMGRJESI
bakong.base-url=https://api-bakong.nbc.gov.kh
bakong.merchant-account=sovann_mengty@bkrt
bakong.currency=USD

telegram.enabled=true
telegram.bot-token=8854616448:AAFmpdYz9vOYHZ7l1stZOoLv3Z_3hkYd_T8
telegram.chat-id=-5016503753
telegram.base-url=https://api.telegram.org
