spring.application.name=report
spring.main.banner-mode=console
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
server.port=${PORT:8010}
app.public-base-url=${APP_PUBLIC_BASE_URL:}

bakong.token=${BAKONG_TOKEN:}
bakong.base-url=${BAKONG_BASE_URL:https://api-bakong.nbc.gov.kh}
bakong.merchant-account=${BAKONG_MERCHANT_ACCOUNT:sovann_mengty@bkrt}
bakong.currency=${BAKONG_CURRENCY:USD}

telegram.enabled=${TELEGRAM_ENABLED:true}
telegram.bot-token=${TELEGRAM_BOT_TOKEN:}
telegram.chat-id=${TELEGRAM_CHAT_ID:}
telegram.base-url=${TELEGRAM_BASE_URL:https://api.telegram.org}

jwt.secret=${JWT_SECRET:change-this-local-jwt-secret-before-production-123456}
jwt.expiration-minutes=${JWT_EXPIRATION_MINUTES:60}
